using Microsoft.CodeAnalysis; // Uninstall this package from my nugnugs if it doesn't work cos this aint netstandard 2.0...

namespace Vvec.Cli.Arguments
{
    public class Saucey : ISourceGenerator
    {
        public void Execute(GeneratorExecutionContext context)
        {
            var source = $@"// <auto-generated/>
using System;
namespace Vvec.Cli.Arguments
{{
  public partial class EntryPoint
  {{
    public partial void SG()
    {{
      System.Console.WriteLine(""Ooooh, saucey!"");
    }}
  }}
}}";
            context.AddSource("EntryPoint.g.cs", source);
        }

        public void Initialize(GeneratorInitializationContext context)
        {
            // nop
        }
    }
}
